imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: admin.yml }
    - { resource: doctrine_extensions.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: %assets_version%
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form_themes:
        - 'MopaBootstrapBundle:Form:fields.html.twig'
        - 'VichUploaderBundle:Form:fields.html.twig'
        - 'SonataCoreBundle:Form:datepicker.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        mapping_types:
            enum:       string
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        dql:
            numeric_functions:
                sin: Kraken\WarmBundle\Query\Mysql\Sin
                cos: Kraken\WarmBundle\Query\Mysql\Cos
                acos: Kraken\WarmBundle\Query\Mysql\Acos
                radians: Kraken\WarmBundle\Query\Mysql\Radians
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        metadata_cache_driver: array
        query_cache_driver: array
        result_cache_driver: array
        #entity_managers:
            #default:
                #mappings:
                    #ApplicationSonataMediaBundle: ~
                    #SonataMediaBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
#     host:       %mailer_host%
#     encryption: %mailer_encryption%
#     auth_mode:  %mailer_auth_mode%
    username:   %mailer_user%
    password:   %mailer_password%
    spool:      { type: memory }

vich_geographical:
    db_driver: orm # or mongodb

stof_doctrine_extensions:
    default_locale: pl_PL
    orm:
        default:
            timestampable: true

mopa_bootstrap:
    form:
        checkbox_label: label
        render_required_asterisk: true
        render_optional_text: false
        horizontal_label_class: col-sm-4
        horizontal_input_wrapper_class: col-sm-8
        collection:
            widget_remove_btn:
                attr:
                    class: btn btn-danger
                label: Usuń tę pozycję z listy
                icon: null
                icon_inverted: false
    menu: ~

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Kraken\RankingBundle\Entity\User

vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
        cover_image:
            uri_prefix:         /uploads/covers
            upload_destination: %kernel.root_dir%/../web/uploads/covers
        cross_section:
            uri_prefix:         /uploads/cross_sections
            upload_destination: %kernel.root_dir%/../web/uploads/cross_sections

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [200, 150], mode: inset }

open_graph_protocol:
    libraries:
        base:
            class: Beyerz\OpenGraphProtocolBundle\Libraries\Base
            default_values:
                site_name: Ranking kotłów CzysteOgrzewanie.pl
                type: website
                title: Ranking kotłów CzysteOgrzewanie.pl
                url: http://ranking.czysteogrzewanie.pl
                image: http://czysteogrzewanie.pl/wp-content/uploads/2013/02/i_like_roofs.jpg
                description: Techniczny przegląd rynku kotłów na węgiel i drewno
        facebook:
            class: Beyerz\OpenGraphProtocolBundle\Libraries\Facebook
            default_values: { app_id: 327276617378519, app_secret: e3138af4b4ec48f465c65aa375f387c1 }

sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false

ivory_ck_editor:
    default_config: default
    configs:
        default:
            filebrowserBrowseRoute: admin_sonata_media_media_ckeditor_browser
            filebrowserImageBrowseRoute: admin_sonata_media_media_ckeditor_browser
            # Display images by default when clicking the image dialog browse button
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            # Upload file as image when sending a file from the image dialog
            filebrowserImageUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image

sonata_formatter:
    ckeditor:
        templates:
            browser: 'SonataFormatterBundle:Ckeditor:browser.html.twig'
            upload: 'SonataFormatterBundle:Ckeditor:upload.html.twig'
