_warm:
    resource: "@KrakenWarmBundle/Resources/config/routing.yml"
    prefix:   /
    host: "cieplowlasciwie.pl"

_main:
    resource: routing.yml

_ranking:
    resource: "@KrakenRankingBundle/Resources/config/routing.yml"
    prefix:   /
    host: "ranking.czysteogrzewanie.pl"
