fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

warm:
    resource: "@KrakenWarmBundle/Resources/config/routing.yml"
    prefix:   /
    host: "cieplowlasciwie.pl"

ranking:
    resource: "@KrakenRankingBundle/Resources/config/routing.yml"
    prefix:   /
    host: "ranking.czysteogrzewanie.pl"
