fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

warm:
    resource: "@KrakenWarmBundle/Resources/config/routing.yml"
    prefix:   /
    host: "cieplowlasciwie.pl"

ranking:
    resource: "@KrakenRankingBundle/Resources/config/routing.yml"
    prefix:   /
    host: "ranking.czysteogrzewanie.pl"
