homepage:
    path:  /
    defaults: { _controller: KrakenWarmBundle:Default:landing }

start:
    path:  /start/{slug}
    defaults: { _controller: KrakenWarmBundle:Calculator:index, slug: ~ }

what:
    path:  /co_to_jest
    defaults: { _controller: KrakenWarmBundle:Default:what }

details:
    path:  /szczegoly/{slug}
    defaults: { _controller: KrakenWarmBundle:Calculator:details }

details_breakdown:
    path:  /details/breakdown/{id}
    defaults: { _controller: KrakenWarmBundle:Calculator:breakdown }
    options:
        expose: true

details_fuels:
    path:  /details/fuels/{id}
    defaults: { _controller: KrakenWarmBundle:Calculator:fuels }
    options:
        expose: true

details_custom_data:
    path:  /details/custom_data/{id}
    defaults: { _controller: KrakenWarmBundle:Calculator:customData }
    options:
        expose: true

result:
    path:  /wynik/{slug}
    defaults: { _controller: KrakenWarmBundle:Calculator:result }

heaters:
    path:  /wynik/{slug}/grzejniki
    defaults: { _controller: KrakenWarmBundle:Calculator:heaters }

old_result:
    path:  /energia/{slug}
    defaults: { _controller: KrakenWarmBundle:Calculator:result }

how_it_works:
    path:  /jak-to-dziala
    defaults: { _controller: KrakenWarmBundle:Default:howItWorks }

why_not_works:
    path:  /czemu-nie-dziala
    defaults: { _controller: KrakenWarmBundle:Default:whyNotWorks }

rules:
    path:  /zasady
    defaults: { _controller: KrakenWarmBundle:Default:rules }

my_results:
    path:  /moje-wyniki
    defaults: { _controller: KrakenWarmBundle:Calculator:myResults }
