# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.boiler:
        class: Kraken\RankingBundle\Admin\BoilerAdmin
        arguments: [~, Kraken\RankingBundle\Entity\Boiler, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Kocioł }
    admin.change:
        class: Kraken\RankingBundle\Admin\ChangeAdmin
        arguments: [~, Kraken\RankingBundle\Entity\Change, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Log zmian, show_in_dashboard: false }
    admin.boiler_power:
        class: Kraken\RankingBundle\Admin\BoilerPowerAdmin
        arguments: [~, Kraken\RankingBundle\Entity\BoilerPower, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Moc kotła, show_in_dashboard: false }
    admin.boiler_fuel_type:
        class: Kraken\RankingBundle\Admin\BoilerFuelTypeAdmin
        arguments: [~, Kraken\RankingBundle\Entity\BoilerFuelType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Obsługiwane paliwa, show_in_dashboard: false }
    admin.fuel_type:
        class: Kraken\RankingBundle\Admin\FuelTypeAdmin
        arguments: [~, Kraken\RankingBundle\Entity\FuelType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Dostępne paliwa }
    admin.notice:
        class: Kraken\RankingBundle\Admin\NoticeAdmin
        arguments: [~, Kraken\RankingBundle\Entity\Notice, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Wady/zalety, show_in_dashboard: false }
    admin.notice_prototype:
        class: Kraken\RankingBundle\Admin\NoticePrototypeAdmin
        arguments: [~, Kraken\RankingBundle\Entity\NoticePrototype, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Prototyp, show_in_dashboard: false }
    admin.manufacturer:
        class: Kraken\RankingBundle\Admin\ManufacturerAdmin
        arguments: [~, Kraken\RankingBundle\Entity\Manufacturer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Producenci }
    admin.review:
        class: Kraken\RankingBundle\Admin\ReviewAdmin
        arguments: [~, Kraken\RankingBundle\Entity\Review, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Opinie }
    admin.review_summary:
        class: Kraken\RankingBundle\Admin\ReviewSummaryAdmin
        arguments: [~, Kraken\RankingBundle\Entity\ReviewSummary, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Podsumowania opinii, show_in_dashboard: false }
    admin.experience:
        class: Kraken\RankingBundle\Admin\ExperienceAdmin
        arguments: [~, Kraken\RankingBundle\Entity\Experience, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Doświadczenia }

    ranking.review_listener:
        class: Kraken\RankingBundle\Listener\ReviewListener
        tags:
            - { name: doctrine.event_subscriber }
