# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.boiler:
        class: Kraken\RankingBundle\Admin\BoilerAdmin
        arguments: [~, Kraken\RankingBundle\Entity\Boiler, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Kocioł }
    admin.change:
        class: Kraken\RankingBundle\Admin\ChangeAdmin
        arguments: [~, Kraken\RankingBundle\Entity\Change, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Log zmian }
    admin.property_value:
        class: Kraken\RankingBundle\Admin\PropertyValueAdmin
        arguments: [~, Kraken\RankingBundle\Entity\PropertyValue, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Cecha kotła }
    admin.boiler_power:
        class: Kraken\RankingBundle\Admin\BoilerPowerAdmin
        arguments: [~, Kraken\RankingBundle\Entity\BoilerPower, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Moc kotła }
    admin.boiler_fuel_type:
        class: Kraken\RankingBundle\Admin\BoilerFuelTypeAdmin
        arguments: [~, Kraken\RankingBundle\Entity\BoilerFuelType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Obsługiwane paliwa }
    admin.fuel_type:
        class: Kraken\RankingBundle\Admin\FuelTypeAdmin
        arguments: [~, Kraken\RankingBundle\Entity\FuelType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Dostępne paliwa }
    admin.notice:
        class: Kraken\RankingBundle\Admin\NoticeAdmin
        arguments: [~, Kraken\RankingBundle\Entity\Notice, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Wady/zalety }
    admin.manufacturer:
        class: Kraken\RankingBundle\Admin\ManufacturerAdmin
        arguments: [~, Kraken\RankingBundle\Entity\Manufacturer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Producenci }
