Feature: Energy balance calculation
  In order to get energy balance calculation
  as a human being
  I want to be able to come here, fill out the form and get that data in my face

  Scenario: Energy calculation for single house
    Given I am on domain "cieplo.dev"
    Given I go to "/"
     When I follow "Sprawdź swój dom!"
     When I select "single_house" from "calculation[building_type]"
      And I press "Dalej"
     Then I should see "Położenie budynku w przestrzeni i czasie"
     When I fill in hidden field "calculation[latitude]" with "51.09"
    Given I fill in hidden field "calculation[longitude]" with "16.98"
     When I select "1980" from "calculation[construction_year]"
      And I press "Dalej"
     Then I should see "Powierzchnia zabudowy"
     When I select "yes" from "calculation[has_area]"
     When I fill in "calculation[area]" with "100"
     When I select "Parterowy" from "calculation[building_floors]"
     When I select "Skośny" from "calculation[building_roof]"
     When I select "1" from "calculation_building_heated_floors_1"
     When I select "2" from "calculation_building_heated_floors_2"
      And I press "Dalej"
     Then I should see "Ściany zewnętrzne"
     When I select "traditional" from "calculation[construction_type]"
     When I fill in "calculation[wall_size]" with "50"
     When I select "Cegła pełna" from "calculation[primary_wall_material]"
     When I select "Styropian" from "calculation[external_isolation_layer][material]"
      And I fill in "calculation[external_isolation_layer][size]" with "15"
     When I select "Współczesne dwuszybowe" from "calculation[windows_type]"
     When I select "Nowe drewniane" from "calculation[doors_type]"
      And I fill in "calculation[number_windows]" with "10"
      And I fill in "calculation[number_doors]" with "2"
      And I press "Dalej"
     Then I should see "Poddasze i parter"
     When I select "Wełna mineralna" from "calculation[top_isolation_layer][material]"
      And I fill in "calculation[top_isolation_layer][size]" with "30"
     When I select "Styropian twardy (XPS)" from "calculation[bottom_isolation_layer][material]"
      And I fill in "calculation[bottom_isolation_layer][size]" with "10"
      And I press "Dalej"
     Then I should see "Jaką temperaturę podać?"
      And I fill in "calculation[indoor_temperature]" with "21"
      And I press "Wynik"
     Then show last response
     Then I should see "A.D. lata 80-te, 170m2 ogrzewane, Otwock i okolice"
      And I should see "50cm, konstrukcja: cegła pełna, izolacja: styropian 15cm"
      And I should see "dach skośny, Wełna mineralna 30cm"
      And I should see "7kW to potrzebna moc grzewcza (C.O. bez CWU)"
